### ISSUE TITLE
Need to add prerequisites

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/catalog#25]
To get users up to speed on OAM quickly, some additional content may be needed.

Some prerequisites，like:
- [Install Crossplane and OAM](https://github.com/oam-dev/crossplane-oam-sample)
- rbac of workload(deployment/statefulset etc.)

**Comment by zzxwill** [comment]
@sunny0826 +1 for your idea.

@wonderflow As for deploying those Workloads and Traits, installing OAM kubernetes runtime [and crossplane] is a prerequisite. So how about we extracting the common prerequisite part from each workload/trait README and putting them in a REAME like https://github.com/oam-dev/catalog/blob/master/workloads/README.md and https://github.com/oam-dev/catalog/blob/master/traits/README.md, or even in https://github.com/oam-dev/catalog/blob/master/README.md?

**Comment by rootsongjc** [comment]
@sunny0826 +1
A detail of getting start guide of OAM on Kubernetes is very necessary so that people can try it quickly.

**Comment by resouer** [comment]
A common prerequisites section LGTM.

**Comment by resouer** [comment]
Also, this should be fixed ASAP: https://github.com/oam-dev/catalog/tree/master/workloads/statefulset#update-rbac-for-oam-appconfig-controller One should install Crossplane, not install RBAC.

**Comment by resouer** [comment]
The common prerequisites could be written here: https://github.com/oam-dev/catalog/blob/master/README.md
