### ISSUE TITLE
env injector trait needed

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/catalog#26]
Inject env to all pod template, including sidecar container.

It will need order to work with sidecar injector trait.

**Comment by resouer** [comment]
Is sidecar injector trait based on SidecarSet (i.e. an existing operational capability)? 

We should avoid jumping into the trap of "patching everything". Developers should be fully free to define `initContainers` in any PodTemplate-able workload (Deployment, StatefulSet etc, but not ContainerizedWorkload).

For ENV override, we should define a "override" trait and deprecate `parameterValues`.
