### ISSUE TITLE
Use ContainerizedWorkload to abstract those components in Istio bookinfo application.

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/catalog#39]
Followed suggestions from @ryanzhang-oss and @resouer , Using ContainerizedWorkload to abstract those components in Istio bookinfo application should be considered.
https://github.com/oam-dev/catalog/pull/37/files#r446783948

```
... think about abstractions (ContainerizedWorkload etc) later. For abstractions, it should be more than a simple ContainerizedWorkload - new Trait and Scope abstractions are needed.
```

**Comment by resouer** [comment]
/hold

this is non-goal for short term.
