### ISSUE TITLE
The link of `statefulsetworkload` should be official repo 

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/catalog#8]
In [ServiceTrait usage](https://github.com/oam-dev/catalog/tree/master/traits/experimental/servicetrait#getting-started), the link for `statefulsetworkload` should be linked to the file from official repo instead of `https://github.com/My-pleasure/statefulsetworkload#getting-started`
![image](https://user-images.githubusercontent.com/2805315/83737087-22a01880-a685-11ea-9677-0f8b9dc050c6.png)

**Comment by zzxwill** [comment]
@My-pleasure Please help check whether this issue has been fixed.

**Comment by My-pleasure** [comment]
@zzxwill ServiceTrait(now called [ServiceExpose](https://github.com/oam-dev/catalog/tree/master/traits/serviceexpose)) doesn't use the link `https://github.com/My-pleasure/statefulsetworkload#getting-started` anymore, so it can be closed now.

**Comment by wonderflow** [comment]
@My-pleasure  thanks
